type Node = {
  node_id: string;
  skill: string;
  resource: string;
  estimated_weeks: number;
  rationale?: string | null;
};

type Edge = {
  source: string;
  target: string;
};

export function buildRoadmapEmail(nodes: Node[], _edges: Edge[], targetRole: string): string {
  const roleLabel = targetRole.trim() || "your target role";
  const totalWeeks = nodes.reduce((s, n) => s + n.estimated_weeks, 0);

  const rows = nodes
    .map(
      (node, i) => `
      <tr style="background:${i % 2 === 0 ? "#ffffff" : "#f9fafb"};">
        <td style="padding:14px 16px;font-weight:700;color:#102036;font-size:15px;
                   border-bottom:1px solid #e8edf3;vertical-align:top;">
          ${i + 1}. ${esc(node.skill)}
          ${node.rationale ? `<p style="margin:4px 0 0;color:#516277;font-size:13px;font-weight:400;">${esc(node.rationale)}</p>` : ""}
        </td>
        <td style="padding:14px 16px;color:#526173;font-size:13px;
                   border-bottom:1px solid #e8edf3;vertical-align:top;white-space:nowrap;">
          ${node.estimated_weeks} week${node.estimated_weeks !== 1 ? "s" : ""}
        </td>
        <td style="padding:14px 16px;color:#0f766e;font-size:12px;
                   border-bottom:1px solid #e8edf3;vertical-align:top;">
          ${esc(node.resource)}
        </td>
      </tr>`,
    )
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Your Career Roadmap</title>
</head>
<body style="margin:0;padding:0;background:#f1f5f9;
             font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0">
    <tr><td align="center" style="padding:40px 16px;">
      <table width="600" cellpadding="0" cellspacing="0"
             style="background:#fff;border-radius:20px;
                    box-shadow:0 4px 24px rgba(15,23,42,.10);overflow:hidden;">

        <!-- Header -->
        <tr>
          <td style="background:linear-gradient(135deg,#0f766e,#1d4ed8);
                     padding:36px 40px;color:#fff;">
            <p style="margin:0 0 6px;font-size:11px;font-weight:700;letter-spacing:.14em;
                      text-transform:uppercase;opacity:.8;">Career Roadmap Studio</p>
            <h1 style="margin:0;font-size:28px;font-weight:800;line-height:1.15;">
              Your learning path is ready.
            </h1>
            <p style="margin:12px 0 0;opacity:.85;font-size:15px;">
              Target role: <strong>${esc(roleLabel)}</strong>
            </p>
          </td>
        </tr>

        <!-- Summary bar -->
        <tr>
          <td style="padding:20px 40px;background:#f8fafc;border-bottom:1px solid #e8edf3;">
            <p style="margin:0;font-size:14px;color:#516277;">
              <strong style="color:#102036;">${nodes.length} skill${nodes.length !== 1 ? "s" : ""}</strong>
              &nbsp;·&nbsp;
              <strong style="color:#102036;">${totalWeeks} week${totalWeeks !== 1 ? "s" : ""}</strong>
              total estimated time
            </p>
          </td>
        </tr>

        <!-- Skill table -->
        <tr><td style="padding:0;">
          <table width="100%" cellpadding="0" cellspacing="0">
            <tr style="background:#f1f5f9;">
              <th style="padding:10px 16px;text-align:left;font-size:11px;font-weight:700;
                         letter-spacing:.1em;text-transform:uppercase;color:#748399;">Skill</th>
              <th style="padding:10px 16px;text-align:left;font-size:11px;font-weight:700;
                         letter-spacing:.1em;text-transform:uppercase;color:#748399;">Time</th>
              <th style="padding:10px 16px;text-align:left;font-size:11px;font-weight:700;
                         letter-spacing:.1em;text-transform:uppercase;color:#748399;">Resource</th>
            </tr>
            ${rows}
          </table>
        </td></tr>

        <!-- Footer -->
        <tr>
          <td style="padding:28px 40px;background:#f8fafc;color:#748399;
                     font-size:12px;border-top:1px solid #e8edf3;">
            Generated by Skill-Bridge Career Navigator.
          </td>
        </tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

/** Escape HTML special chars to prevent injection in the email body. */
function esc(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
